# Generated by Django 3.2.7 on 2021-09-12 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('data', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(default='Event/default.jpg', upload_to='Event/')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL)),
                ('is_liked', models.ManyToManyField(null=True, related_name='is_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
