# Generated by Django 3.2.7 on 2021-09-12 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
